version: "3.7"

services:
  lijin_triton_dev:
    image: ubuntu2204-cpp-triton-dev:latest
    container_name: lijin_triton_dev_container
    ports:
      - "21022:22"               # ssh端口
      - "21100-21200:21100-21200"
    volumes:
      - ~/docker:/root/host
    cap_add:
      - ALL
    tty: true
    privileged: true
    ipc: host
    pid: host
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu","video","display","graphics","utility"]
